openapi: 3.0.1
info:
  title: "Position Service - TraderX"
  version: "1.0"
paths:
  /health:
    get:
      operationId: health
      responses:
        "200":
          description: Simple Healthcheck Endpoint
          content:
            "application/json":
              schema:
                type: object
                example: { "State" : "HEALTHY" }
  /trades:
    get:
      operationId: getTradesByAccount
      description: "Gets trades for a specific account"
      parameters: 
        - in: query
          name: account_id
          required: true
          schema:
            type: integer
            format: int32
          description: "The ID of the account"
      responses:
        '200':
          description: An array of all trades for a specific account
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trade'
  /positions:
    get:
      operationId: getPositionsByAccount
      description: "Gets all Positions for a specific account"
      parameters: 
        - in: query
          name: account_id
          required: true
          schema:
            type: integer
            format: int32
          description: "The ID of the account"
      responses:
        '200':
          description: An array of all positions for a specific account
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Position'
  
components:
  schemas:
    Position:
      type: object
      properties:
        accountId:
          type: integer
          format: int32
          example: 10001
        quantity:
          type: integer
          format: int32
          example: -2000
        security:
          type: string
          example: "XXXY"
        updated:
          type: string
          format: date-time
    Trade:
      type: object
      properties:
        accountId:
          type: integer
          format: int32
          example: 100001
        id:
          type: string
          description: "Trade ID (unique ID)"
          example: "01AN4Z07BY79KA1307SR9X4MV3"
        created:
          type: string
          format: date-time
        quantity:
          type: integer
          format: int32
        security:
          type: string
          example: 'XXXY'
        state:
          type: string
          example: 'Settled'
        side:
          type: string
          example: 'Buy or Sell'
        updated: 
          type: string
          format: date-time
