openapi: 3.0.1
info:
  title: FINOS TraderX Trade Service
  version: 0.1.0
servers:
  - url: ''
paths:
  /trade/:
    post:
      tags:
        - trade-order-controller
      operationId: createTradeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TradeOrder'
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/TradeOrder'
components:
  schemas:
    TradeOrder:
      type: object
      properties:
        id:
          type: string
          example: 'ABC-123-XYZ'
        state:
          type: string
          example: 'New'
        security:
          type: string
          example: 'ADBE'
        quantity:
          type: integer
          format: int32
          example: 100
        accountID:
          type: integer
          format: int32
          example: 22214
        side:
          type: string
          enum:
            - Buy
            - Sell
